config/routes.rb
Rails.application.routes.draw do
  resources :contents
  devise_for :users
  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'about' => 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
	belongs_to :user
	has_attached_file :cover
  	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/,
  	message: "Solo le immagini sono supportate"

  	has_attached_file :allegato
  	validates_attachment_content_type :allegato, :content_type => [ /^image\/(png|gif|jpeg)/,'application/msword'],
  	message: "Formato non supportato"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:edit, :update, :destroy]


  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all.order("created_at DESC")
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = current_user.contents.build
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = current_user.contents.build(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json {head :no_content}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def content_params
      params.require(:content).permit(:titolo, :descrizione, :price, :cover, :allegato)
    end

    #checko l'utente per le modifiche cancellazioni
    def check_user
      if current_user != @content.user
        redirect_to root_url, alert: "Scusa ma non hai accesso a questa pagina"
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contents/_form.html.erb
<%= form_for @content, html: { multipart: true }  do |form| %>

  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
        <% content.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <label class="orange-text">Carica il contenuto digitale che vuoi vendere, formati supportati ....</label>
      <br/>
      <%= form.file_field :allegato %>
  </div>

  <div class="field">
    <%= form.label :titolo %>
    <%= form.text_field :titolo %>
  </div>

  <div class="field">
    <%= form.label :descrizione %>
    <%= form.text_area :descrizione, class: "materialize-textarea" %>
  </div>

  <div class="field">
    <%= form.label :Prezzo %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <label class="orange-text">Carica un immagina da utilizzare per il tuo contenuto digitale</label>
    <br/>
    <%= form.file_field :cover %>
  </div>

  <br/>
  <div class="actions">
    <%= form.submit 'Salva contenuto', class: "btn btn-form"%>
  </div>
  <br/>
<% end %>

app/views/contents/edit.html.erb
<h1 class="center">Modifica contenuto <%=@content.titolo %></h1>

<%= render 'form', content: @content %>

<%= link_to 'Mostra', @content %> |
<%= link_to 'Torna ai contenuti', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<!--<h1>Contents</h1>-->

<div class="row">
  <% @contents.each do |content| %>
    <div class="col s4">
      <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag content.cover.url, class: "activator" %>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= content.titolo %><i class="material-icons right">more_vert</i></span>
          <div>
            <span>Venduto da <%= content.user.name %></span>
            <span class="right"><%= number_to_currency(content.price) %></span>
          </div>
          <br/>
          <div class="center">
              <%= link_to 'Scopri di più', content_path(content) , class: "btn" %>
          </div>
          <% if content.user == current_user %>
          <br/>
            <div class="center">
              <p>
                <%= link_to 'Edit', edit_content_path(content) %> 
               <%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Sei sicuro?' } %></p>
             </div>
          <% end %>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4">C%= content.titolo %><i class="material-icons right">close</i></span>
          <p><%= content.descrizione %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>





<br>

app/views/contents/new.html.erb
<h1 class="center">Vendi un contenuto digitale</h1>

<%= render 'form', content: @content %>

<%= link_to 'Torna ai contenuti', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
	<div class="col l6">
		<%= image_tag @content.cover.url, class: "responsive-img show-img" %>
	</div>
	<div class="col l6">
		<h1 class="show-titolo"><%= @content.titolo %></h1>		 
		<h4 classs="show-prezzo"><%= number_to_currency(@content.price )%></h4>
		<p>Venduto da <%= @content.user.name %></p>		
		<p><%= @content.descrizione %></p>
	</div>
</div>
<% if @content.user == current_user %>
		<%= link_to 'Edit', edit_content_path(@content) %> |
	<% end %>	
	<%= link_to 'Torna ai contenuti', contents_path %>


		

app/views/layouts/_footer.html.erb
<footer class="page-footer light-blue darken-4">
  <div class="footer-copyright">
    <div class="container">
		<div class="row">
			<div class="col s4">© 2020 Copyright MoiseMarket</div>
	      	<div class="col s4">Spcial</div>
	      	<div class="col s4"><%= link_to "about", about_path, class:"grey-text text-lighten-4 right" %></div>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed">
	<nav class="light-blue darken-4">
		<div class="container nav-wrapper">
		  <%= link_to "MoiseMarket", root_path, class:"brand-logo"%>
      	  <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
		  <ul class="right hide-on-med-and-down">
	  		<li><%= link_to 'Vendi contenuti', new_content_path %></li>
		    <% if user_signed_in? %>
		    	<li><%= link_to "Log out", destroy_user_session_path, method: :delete, data: { confirm: 'Sei sicuro?' }%></li>
	    	<% else %>
			    <li><%= link_to "Log in", new_user_session_path %></li>
			    <li><%= link_to "Registrazione", new_user_registration_path %></li>
		    <% end %>
		  </ul>
		  <ul class="sidenav id=mobile-demo">
		  	<li><%= link_to 'Vendi contenuti', new_content_path %></li>
		    <% if user_signed_in? %>
		    	<li><%= link_to "Log out", destroy_user_session_path, method: :delete, data: { confirm: 'Sei sicuro?' }%></li>
	    	<% else %>
			    <li><%= link_to "Log in", new_user_session_path %></li>
			    <li><%= link_to "Registrazione", new_user_registration_path %></li>
		    <% end %>
		  </ul>
		</div>
	</nav>
	
</header>		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoiseMarket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

  <main class="container">
    <%= yield %>
  </main>
  <%= render "layouts/footer" %>
  </body>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
      var elems = document.querySelectorAll('.sidenav');
      var instances = M.Sidenav.init(elems, options);
    });

    // Or with jQuery

    $(document).ready(function(){
      $('.sidenav').sidenav();
    });  
    </script>
</html>

app/views/pages/about.html.erb
<h1>Chi siamo</h1>
<p>Sono un programmatore</p

app/views/pages/home.html.erb
<h1>Benvenuto</h1>
<p>Per saperne di più <%= link_to "clicca qui", about_path%></p>